/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AcaoAlteracaoProposta;
import io.swagger.client.model.IndicativoSimNao;
import io.swagger.client.model.PreEfetivacaoPropostaRequest;
import io.swagger.client.model.Proposta;
import java.io.IOException;

/**
 * Objeto de entrada para a alteração da proposta.
 */
@ApiModel(description = "Objeto de entrada para a alteração da proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class AlteracaoPropostaRequest {
  @SerializedName("acaoAlteracao")
  private AcaoAlteracaoProposta acaoAlteracao = null;

  @SerializedName("uploadConfirmado")
  private IndicativoSimNao uploadConfirmado = null;

  @SerializedName("preEfetivacaoProposta")
  private PreEfetivacaoPropostaRequest preEfetivacaoProposta = null;

  @SerializedName("proposta")
  private Proposta proposta = null;

  public AlteracaoPropostaRequest acaoAlteracao(AcaoAlteracaoProposta acaoAlteracao) {
    this.acaoAlteracao = acaoAlteracao;
    return this;
  }

   /**
   * Get acaoAlteracao
   * @return acaoAlteracao
  **/
  @ApiModelProperty(value = "")
  public AcaoAlteracaoProposta getAcaoAlteracao() {
    return acaoAlteracao;
  }

  public void setAcaoAlteracao(AcaoAlteracaoProposta acaoAlteracao) {
    this.acaoAlteracao = acaoAlteracao;
  }

  public AlteracaoPropostaRequest uploadConfirmado(IndicativoSimNao uploadConfirmado) {
    this.uploadConfirmado = uploadConfirmado;
    return this;
  }

   /**
   * Get uploadConfirmado
   * @return uploadConfirmado
  **/
  @ApiModelProperty(value = "")
  public IndicativoSimNao getUploadConfirmado() {
    return uploadConfirmado;
  }

  public void setUploadConfirmado(IndicativoSimNao uploadConfirmado) {
    this.uploadConfirmado = uploadConfirmado;
  }

  public AlteracaoPropostaRequest preEfetivacaoProposta(PreEfetivacaoPropostaRequest preEfetivacaoProposta) {
    this.preEfetivacaoProposta = preEfetivacaoProposta;
    return this;
  }

   /**
   * Get preEfetivacaoProposta
   * @return preEfetivacaoProposta
  **/
  @ApiModelProperty(value = "")
  public PreEfetivacaoPropostaRequest getPreEfetivacaoProposta() {
    return preEfetivacaoProposta;
  }

  public void setPreEfetivacaoProposta(PreEfetivacaoPropostaRequest preEfetivacaoProposta) {
    this.preEfetivacaoProposta = preEfetivacaoProposta;
  }

  public AlteracaoPropostaRequest proposta(Proposta proposta) {
    this.proposta = proposta;
    return this;
  }

   /**
   * Get proposta
   * @return proposta
  **/
  @ApiModelProperty(value = "")
  public Proposta getProposta() {
    return proposta;
  }

  public void setProposta(Proposta proposta) {
    this.proposta = proposta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlteracaoPropostaRequest alteracaoPropostaRequest = (AlteracaoPropostaRequest) o;
    return Objects.equals(this.acaoAlteracao, alteracaoPropostaRequest.acaoAlteracao) &&
        Objects.equals(this.uploadConfirmado, alteracaoPropostaRequest.uploadConfirmado) &&
        Objects.equals(this.preEfetivacaoProposta, alteracaoPropostaRequest.preEfetivacaoProposta) &&
        Objects.equals(this.proposta, alteracaoPropostaRequest.proposta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acaoAlteracao, uploadConfirmado, preEfetivacaoProposta, proposta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlteracaoPropostaRequest {\n");
    
    sb.append("    acaoAlteracao: ").append(toIndentedString(acaoAlteracao)).append("\n");
    sb.append("    uploadConfirmado: ").append(toIndentedString(uploadConfirmado)).append("\n");
    sb.append("    preEfetivacaoProposta: ").append(toIndentedString(preEfetivacaoProposta)).append("\n");
    sb.append("    proposta: ").append(toIndentedString(proposta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

