/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entidade representando um cartão de crédito.
 */
@ApiModel(description = "Entidade representando um cartão de crédito.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class CartaoCredito {
  @SerializedName("emissor")
  private String emissor = null;

  @SerializedName("limiteCredito")
  private Double limiteCredito = null;

  public CartaoCredito emissor(String emissor) {
    this.emissor = emissor;
    return this;
  }

   /**
   * Código do emissor do cartão de crédito.
   * @return emissor
  **/
  @ApiModelProperty(value = "Código do emissor do cartão de crédito.")
  public String getEmissor() {
    return emissor;
  }

  public void setEmissor(String emissor) {
    this.emissor = emissor;
  }

  public CartaoCredito limiteCredito(Double limiteCredito) {
    this.limiteCredito = limiteCredito;
    return this;
  }

   /**
   * Limite de crédito do cartão.
   * @return limiteCredito
  **/
  @ApiModelProperty(value = "Limite de crédito do cartão.")
  public Double getLimiteCredito() {
    return limiteCredito;
  }

  public void setLimiteCredito(Double limiteCredito) {
    this.limiteCredito = limiteCredito;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CartaoCredito cartaoCredito = (CartaoCredito) o;
    return Objects.equals(this.emissor, cartaoCredito.emissor) &&
        Objects.equals(this.limiteCredito, cartaoCredito.limiteCredito);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emissor, limiteCredito);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CartaoCredito {\n");
    
    sb.append("    emissor: ").append(toIndentedString(emissor)).append("\n");
    sb.append("    limiteCredito: ").append(toIndentedString(limiteCredito)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

