/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entidade representando o cheque usado na proposta.
 */
@ApiModel(description = "Entidade representando o cheque usado na proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Cheque {
  @SerializedName("cmc7")
  private String cmc7 = null;

  @SerializedName("parcela")
  private String parcela = null;

  @SerializedName("vencimento")
  private String vencimento = null;

  public Cheque cmc7(String cmc7) {
    this.cmc7 = cmc7;
    return this;
  }

   /**
   * CMC7 do cheque.
   * @return cmc7
  **/
  @ApiModelProperty(value = "CMC7 do cheque.")
  public String getCmc7() {
    return cmc7;
  }

  public void setCmc7(String cmc7) {
    this.cmc7 = cmc7;
  }

  public Cheque parcela(String parcela) {
    this.parcela = parcela;
    return this;
  }

   /**
   * Parcela do cheque.
   * @return parcela
  **/
  @ApiModelProperty(value = "Parcela do cheque.")
  public String getParcela() {
    return parcela;
  }

  public void setParcela(String parcela) {
    this.parcela = parcela;
  }

  public Cheque vencimento(String vencimento) {
    this.vencimento = vencimento;
    return this;
  }

   /**
   * Vencimento do cheque.
   * @return vencimento
  **/
  @ApiModelProperty(value = "Vencimento do cheque.")
  public String getVencimento() {
    return vencimento;
  }

  public void setVencimento(String vencimento) {
    this.vencimento = vencimento;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cheque cheque = (Cheque) o;
    return Objects.equals(this.cmc7, cheque.cmc7) &&
        Objects.equals(this.parcela, cheque.parcela) &&
        Objects.equals(this.vencimento, cheque.vencimento);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cmc7, parcela, vencimento);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cheque {\n");
    
    sb.append("    cmc7: ").append(toIndentedString(cmc7)).append("\n");
    sb.append("    parcela: ").append(toIndentedString(parcela)).append("\n");
    sb.append("    vencimento: ").append(toIndentedString(vencimento)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

