/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Emprego;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Entidade representando um conjuge do cliente da proposta.
 */
@ApiModel(description = "Entidade representando um conjuge do cliente da proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Conjuge {
  @SerializedName("cpf")
  private String cpf = null;

  @SerializedName("dataNascimento")
  private LocalDate dataNascimento = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("emprego")
  private Emprego emprego = null;

  public Conjuge cpf(String cpf) {
    this.cpf = cpf;
    return this;
  }

   /**
   * Cpf do conjuge.
   * @return cpf
  **/
  @ApiModelProperty(value = "Cpf do conjuge.")
  public String getCpf() {
    return cpf;
  }

  public void setCpf(String cpf) {
    this.cpf = cpf;
  }

  public Conjuge dataNascimento(LocalDate dataNascimento) {
    this.dataNascimento = dataNascimento;
    return this;
  }

   /**
   * Data de nascimento do conjuge.
   * @return dataNascimento
  **/
  @ApiModelProperty(value = "Data de nascimento do conjuge.")
  public LocalDate getDataNascimento() {
    return dataNascimento;
  }

  public void setDataNascimento(LocalDate dataNascimento) {
    this.dataNascimento = dataNascimento;
  }

  public Conjuge nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome do conjuge.
   * @return nome
  **/
  @ApiModelProperty(value = "Nome do conjuge.")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public Conjuge emprego(Emprego emprego) {
    this.emprego = emprego;
    return this;
  }

   /**
   * Get emprego
   * @return emprego
  **/
  @ApiModelProperty(value = "")
  public Emprego getEmprego() {
    return emprego;
  }

  public void setEmprego(Emprego emprego) {
    this.emprego = emprego;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Conjuge conjuge = (Conjuge) o;
    return Objects.equals(this.cpf, conjuge.cpf) &&
        Objects.equals(this.dataNascimento, conjuge.dataNascimento) &&
        Objects.equals(this.nome, conjuge.nome) &&
        Objects.equals(this.emprego, conjuge.emprego);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpf, dataNascimento, nome, emprego);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Conjuge {\n");
    
    sb.append("    cpf: ").append(toIndentedString(cpf)).append("\n");
    sb.append("    dataNascimento: ").append(toIndentedString(dataNascimento)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    emprego: ").append(toIndentedString(emprego)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

