/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TipoConta;
import io.swagger.client.model.TipoContaBancaria;
import java.io.IOException;

/**
 * Entidade representando uma conta bancária.
 */
@ApiModel(description = "Entidade representando uma conta bancária.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class ContaBancaria {
  @SerializedName("codigoBanco")
  private String codigoBanco = null;

  @SerializedName("tipoContaBancaria")
  private TipoContaBancaria tipoContaBancaria = null;

  @SerializedName("codigoAgencia")
  private String codigoAgencia = null;

  @SerializedName("conta")
  private String conta = null;

  @SerializedName("cidade")
  private String cidade = null;

  @SerializedName("uf")
  private String uf = null;

  @SerializedName("tempoMes")
  private Integer tempoMes = null;

  @SerializedName("tempoAno")
  private Integer tempoAno = null;

  @SerializedName("limiteChequeEspecial")
  private Double limiteChequeEspecial = null;

  @SerializedName("tipoConta")
  private TipoConta tipoConta = null;

  public ContaBancaria codigoBanco(String codigoBanco) {
    this.codigoBanco = codigoBanco;
    return this;
  }

   /**
   * Código do banco.
   * @return codigoBanco
  **/
  @ApiModelProperty(value = "Código do banco.")
  public String getCodigoBanco() {
    return codigoBanco;
  }

  public void setCodigoBanco(String codigoBanco) {
    this.codigoBanco = codigoBanco;
  }

  public ContaBancaria tipoContaBancaria(TipoContaBancaria tipoContaBancaria) {
    this.tipoContaBancaria = tipoContaBancaria;
    return this;
  }

   /**
   * Get tipoContaBancaria
   * @return tipoContaBancaria
  **/
  @ApiModelProperty(value = "")
  public TipoContaBancaria getTipoContaBancaria() {
    return tipoContaBancaria;
  }

  public void setTipoContaBancaria(TipoContaBancaria tipoContaBancaria) {
    this.tipoContaBancaria = tipoContaBancaria;
  }

  public ContaBancaria codigoAgencia(String codigoAgencia) {
    this.codigoAgencia = codigoAgencia;
    return this;
  }

   /**
   * Código da agência.
   * @return codigoAgencia
  **/
  @ApiModelProperty(value = "Código da agência.")
  public String getCodigoAgencia() {
    return codigoAgencia;
  }

  public void setCodigoAgencia(String codigoAgencia) {
    this.codigoAgencia = codigoAgencia;
  }

  public ContaBancaria conta(String conta) {
    this.conta = conta;
    return this;
  }

   /**
   * Número da conta.
   * @return conta
  **/
  @ApiModelProperty(value = "Número da conta.")
  public String getConta() {
    return conta;
  }

  public void setConta(String conta) {
    this.conta = conta;
  }

  public ContaBancaria cidade(String cidade) {
    this.cidade = cidade;
    return this;
  }

   /**
   * Cidade do banco da abertura da conta.
   * @return cidade
  **/
  @ApiModelProperty(value = "Cidade do banco da abertura da conta.")
  public String getCidade() {
    return cidade;
  }

  public void setCidade(String cidade) {
    this.cidade = cidade;
  }

  public ContaBancaria uf(String uf) {
    this.uf = uf;
    return this;
  }

   /**
   * Unidade federativa do banco da abertura da conta.
   * @return uf
  **/
  @ApiModelProperty(value = "Unidade federativa do banco da abertura da conta.")
  public String getUf() {
    return uf;
  }

  public void setUf(String uf) {
    this.uf = uf;
  }

  public ContaBancaria tempoMes(Integer tempoMes) {
    this.tempoMes = tempoMes;
    return this;
  }

   /**
   * Desde que mês o cliente tem essa conta.
   * @return tempoMes
  **/
  @ApiModelProperty(value = "Desde que mês o cliente tem essa conta.")
  public Integer getTempoMes() {
    return tempoMes;
  }

  public void setTempoMes(Integer tempoMes) {
    this.tempoMes = tempoMes;
  }

  public ContaBancaria tempoAno(Integer tempoAno) {
    this.tempoAno = tempoAno;
    return this;
  }

   /**
   * Desde que ano o cliente tem essa conta.
   * @return tempoAno
  **/
  @ApiModelProperty(value = "Desde que ano o cliente tem essa conta.")
  public Integer getTempoAno() {
    return tempoAno;
  }

  public void setTempoAno(Integer tempoAno) {
    this.tempoAno = tempoAno;
  }

  public ContaBancaria limiteChequeEspecial(Double limiteChequeEspecial) {
    this.limiteChequeEspecial = limiteChequeEspecial;
    return this;
  }

   /**
   * Valor do limite do cheque especial.
   * @return limiteChequeEspecial
  **/
  @ApiModelProperty(value = "Valor do limite do cheque especial.")
  public Double getLimiteChequeEspecial() {
    return limiteChequeEspecial;
  }

  public void setLimiteChequeEspecial(Double limiteChequeEspecial) {
    this.limiteChequeEspecial = limiteChequeEspecial;
  }

  public ContaBancaria tipoConta(TipoConta tipoConta) {
    this.tipoConta = tipoConta;
    return this;
  }

   /**
   * Get tipoConta
   * @return tipoConta
  **/
  @ApiModelProperty(value = "")
  public TipoConta getTipoConta() {
    return tipoConta;
  }

  public void setTipoConta(TipoConta tipoConta) {
    this.tipoConta = tipoConta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContaBancaria contaBancaria = (ContaBancaria) o;
    return Objects.equals(this.codigoBanco, contaBancaria.codigoBanco) &&
        Objects.equals(this.tipoContaBancaria, contaBancaria.tipoContaBancaria) &&
        Objects.equals(this.codigoAgencia, contaBancaria.codigoAgencia) &&
        Objects.equals(this.conta, contaBancaria.conta) &&
        Objects.equals(this.cidade, contaBancaria.cidade) &&
        Objects.equals(this.uf, contaBancaria.uf) &&
        Objects.equals(this.tempoMes, contaBancaria.tempoMes) &&
        Objects.equals(this.tempoAno, contaBancaria.tempoAno) &&
        Objects.equals(this.limiteChequeEspecial, contaBancaria.limiteChequeEspecial) &&
        Objects.equals(this.tipoConta, contaBancaria.tipoConta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codigoBanco, tipoContaBancaria, codigoAgencia, conta, cidade, uf, tempoMes, tempoAno, limiteChequeEspecial, tipoConta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContaBancaria {\n");
    
    sb.append("    codigoBanco: ").append(toIndentedString(codigoBanco)).append("\n");
    sb.append("    tipoContaBancaria: ").append(toIndentedString(tipoContaBancaria)).append("\n");
    sb.append("    codigoAgencia: ").append(toIndentedString(codigoAgencia)).append("\n");
    sb.append("    conta: ").append(toIndentedString(conta)).append("\n");
    sb.append("    cidade: ").append(toIndentedString(cidade)).append("\n");
    sb.append("    uf: ").append(toIndentedString(uf)).append("\n");
    sb.append("    tempoMes: ").append(toIndentedString(tempoMes)).append("\n");
    sb.append("    tempoAno: ").append(toIndentedString(tempoAno)).append("\n");
    sb.append("    limiteChequeEspecial: ").append(toIndentedString(limiteChequeEspecial)).append("\n");
    sb.append("    tipoConta: ").append(toIndentedString(tipoConta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

