/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Entidade representando informações adicionais da proposta.
 */
@ApiModel(description = "Entidade representando informações adicionais da proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class DadoAdicional {
  @SerializedName("campo")
  private String campo = null;

  @SerializedName("valor")
  private String valor = null;

  public DadoAdicional campo(String campo) {
    this.campo = campo;
    return this;
  }

   /**
   * Campo da informação.
   * @return campo
  **/
  @ApiModelProperty(value = "Campo da informação.")
  public String getCampo() {
    return campo;
  }

  public void setCampo(String campo) {
    this.campo = campo;
  }

  public DadoAdicional valor(String valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Valor da informação.
   * @return valor
  **/
  @ApiModelProperty(value = "Valor da informação.")
  public String getValor() {
    return valor;
  }

  public void setValor(String valor) {
    this.valor = valor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadoAdicional dadoAdicional = (DadoAdicional) o;
    return Objects.equals(this.campo, dadoAdicional.campo) &&
        Objects.equals(this.valor, dadoAdicional.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(campo, valor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadoAdicional {\n");
    
    sb.append("    campo: ").append(toIndentedString(campo)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

