/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TipoContaBancaria;
import java.io.IOException;

/**
 * Entidade representando os dados de liberação da proposta.
 */
@ApiModel(description = "Entidade representando os dados de liberação da proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class DadosLiberacao {
  @SerializedName("agencia")
  private String agencia = null;

  @SerializedName("banco")
  private String banco = null;

  @SerializedName("beneficiario")
  private String beneficiario = null;

  @SerializedName("conta")
  private String conta = null;

  @SerializedName("cpfCnpj")
  private String cpfCnpj = null;

  @SerializedName("tipoContaBancaria")
  private TipoContaBancaria tipoContaBancaria = null;

  public DadosLiberacao agencia(String agencia) {
    this.agencia = agencia;
    return this;
  }

   /**
   * Agência para liberação.
   * @return agencia
  **/
  @ApiModelProperty(value = "Agência para liberação.")
  public String getAgencia() {
    return agencia;
  }

  public void setAgencia(String agencia) {
    this.agencia = agencia;
  }

  public DadosLiberacao banco(String banco) {
    this.banco = banco;
    return this;
  }

   /**
   * Banco para liberação.
   * @return banco
  **/
  @ApiModelProperty(value = "Banco para liberação.")
  public String getBanco() {
    return banco;
  }

  public void setBanco(String banco) {
    this.banco = banco;
  }

  public DadosLiberacao beneficiario(String beneficiario) {
    this.beneficiario = beneficiario;
    return this;
  }

   /**
   * Beneficiário para liberação.
   * @return beneficiario
  **/
  @ApiModelProperty(value = "Beneficiário para liberação.")
  public String getBeneficiario() {
    return beneficiario;
  }

  public void setBeneficiario(String beneficiario) {
    this.beneficiario = beneficiario;
  }

  public DadosLiberacao conta(String conta) {
    this.conta = conta;
    return this;
  }

   /**
   * Conta para liberação.
   * @return conta
  **/
  @ApiModelProperty(value = "Conta para liberação.")
  public String getConta() {
    return conta;
  }

  public void setConta(String conta) {
    this.conta = conta;
  }

  public DadosLiberacao cpfCnpj(String cpfCnpj) {
    this.cpfCnpj = cpfCnpj;
    return this;
  }

   /**
   * Cpf ou Cnpj para liberação.
   * @return cpfCnpj
  **/
  @ApiModelProperty(value = "Cpf ou Cnpj para liberação.")
  public String getCpfCnpj() {
    return cpfCnpj;
  }

  public void setCpfCnpj(String cpfCnpj) {
    this.cpfCnpj = cpfCnpj;
  }

  public DadosLiberacao tipoContaBancaria(TipoContaBancaria tipoContaBancaria) {
    this.tipoContaBancaria = tipoContaBancaria;
    return this;
  }

   /**
   * Get tipoContaBancaria
   * @return tipoContaBancaria
  **/
  @ApiModelProperty(value = "")
  public TipoContaBancaria getTipoContaBancaria() {
    return tipoContaBancaria;
  }

  public void setTipoContaBancaria(TipoContaBancaria tipoContaBancaria) {
    this.tipoContaBancaria = tipoContaBancaria;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DadosLiberacao dadosLiberacao = (DadosLiberacao) o;
    return Objects.equals(this.agencia, dadosLiberacao.agencia) &&
        Objects.equals(this.banco, dadosLiberacao.banco) &&
        Objects.equals(this.beneficiario, dadosLiberacao.beneficiario) &&
        Objects.equals(this.conta, dadosLiberacao.conta) &&
        Objects.equals(this.cpfCnpj, dadosLiberacao.cpfCnpj) &&
        Objects.equals(this.tipoContaBancaria, dadosLiberacao.tipoContaBancaria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agencia, banco, beneficiario, conta, cpfCnpj, tipoContaBancaria);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DadosLiberacao {\n");
    
    sb.append("    agencia: ").append(toIndentedString(agencia)).append("\n");
    sb.append("    banco: ").append(toIndentedString(banco)).append("\n");
    sb.append("    beneficiario: ").append(toIndentedString(beneficiario)).append("\n");
    sb.append("    conta: ").append(toIndentedString(conta)).append("\n");
    sb.append("    cpfCnpj: ").append(toIndentedString(cpfCnpj)).append("\n");
    sb.append("    tipoContaBancaria: ").append(toIndentedString(tipoContaBancaria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

