/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Entidade representando um documento de um cliente.
 */
@ApiModel(description = "Entidade representando um documento de um cliente.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Documento {
  @SerializedName("numero")
  private String numero = null;

  @SerializedName("codigoTipoDocumento")
  private String codigoTipoDocumento = null;

  @SerializedName("codigoOrgaoEmissor")
  private String codigoOrgaoEmissor = null;

  @SerializedName("dataEmissao")
  private LocalDate dataEmissao = null;

  @SerializedName("uf")
  private String uf = null;

  public Documento numero(String numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Número do documento.
   * @return numero
  **/
  @ApiModelProperty(value = "Número do documento.")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public Documento codigoTipoDocumento(String codigoTipoDocumento) {
    this.codigoTipoDocumento = codigoTipoDocumento;
    return this;
  }

   /**
   * Código do Tipo do documento.
   * @return codigoTipoDocumento
  **/
  @ApiModelProperty(value = "Código do Tipo do documento.")
  public String getCodigoTipoDocumento() {
    return codigoTipoDocumento;
  }

  public void setCodigoTipoDocumento(String codigoTipoDocumento) {
    this.codigoTipoDocumento = codigoTipoDocumento;
  }

  public Documento codigoOrgaoEmissor(String codigoOrgaoEmissor) {
    this.codigoOrgaoEmissor = codigoOrgaoEmissor;
    return this;
  }

   /**
   * Código do órgão emissor do documento.
   * @return codigoOrgaoEmissor
  **/
  @ApiModelProperty(value = "Código do órgão emissor do documento.")
  public String getCodigoOrgaoEmissor() {
    return codigoOrgaoEmissor;
  }

  public void setCodigoOrgaoEmissor(String codigoOrgaoEmissor) {
    this.codigoOrgaoEmissor = codigoOrgaoEmissor;
  }

  public Documento dataEmissao(LocalDate dataEmissao) {
    this.dataEmissao = dataEmissao;
    return this;
  }

   /**
   * Data da emissão do documento.
   * @return dataEmissao
  **/
  @ApiModelProperty(value = "Data da emissão do documento.")
  public LocalDate getDataEmissao() {
    return dataEmissao;
  }

  public void setDataEmissao(LocalDate dataEmissao) {
    this.dataEmissao = dataEmissao;
  }

  public Documento uf(String uf) {
    this.uf = uf;
    return this;
  }

   /**
   * Unidade federativa do documento.
   * @return uf
  **/
  @ApiModelProperty(value = "Unidade federativa do documento.")
  public String getUf() {
    return uf;
  }

  public void setUf(String uf) {
    this.uf = uf;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Documento documento = (Documento) o;
    return Objects.equals(this.numero, documento.numero) &&
        Objects.equals(this.codigoTipoDocumento, documento.codigoTipoDocumento) &&
        Objects.equals(this.codigoOrgaoEmissor, documento.codigoOrgaoEmissor) &&
        Objects.equals(this.dataEmissao, documento.dataEmissao) &&
        Objects.equals(this.uf, documento.uf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, codigoTipoDocumento, codigoOrgaoEmissor, dataEmissao, uf);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Documento {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    codigoTipoDocumento: ").append(toIndentedString(codigoTipoDocumento)).append("\n");
    sb.append("    codigoOrgaoEmissor: ").append(toIndentedString(codigoOrgaoEmissor)).append("\n");
    sb.append("    dataEmissao: ").append(toIndentedString(dataEmissao)).append("\n");
    sb.append("    uf: ").append(toIndentedString(uf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

