/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TipoCorrespondencia;
import io.swagger.client.model.TipoResidencia;
import java.io.IOException;

/**
 * Entidade representando um endereco.
 */
@ApiModel(description = "Entidade representando um endereco.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Endereco {
  @SerializedName("logradouro")
  private String logradouro = null;

  @SerializedName("numero")
  private String numero = null;

  @SerializedName("complemento")
  private String complemento = null;

  @SerializedName("bairro")
  private String bairro = null;

  @SerializedName("cidade")
  private String cidade = null;

  @SerializedName("uf")
  private String uf = null;

  @SerializedName("cep")
  private Long cep = null;

  @SerializedName("tempoMes")
  private Integer tempoMes = null;

  @SerializedName("tempoAno")
  private Integer tempoAno = null;

  @SerializedName("tipoResidencia")
  private TipoResidencia tipoResidencia = null;

  @SerializedName("tipoCorrespondencia")
  private TipoCorrespondencia tipoCorrespondencia = null;

  public Endereco logradouro(String logradouro) {
    this.logradouro = logradouro;
    return this;
  }

   /**
   * Logradouro.
   * @return logradouro
  **/
  @ApiModelProperty(value = "Logradouro.")
  public String getLogradouro() {
    return logradouro;
  }

  public void setLogradouro(String logradouro) {
    this.logradouro = logradouro;
  }

  public Endereco numero(String numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Número.
   * @return numero
  **/
  @ApiModelProperty(value = "Número.")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public Endereco complemento(String complemento) {
    this.complemento = complemento;
    return this;
  }

   /**
   * Complemento.
   * @return complemento
  **/
  @ApiModelProperty(value = "Complemento.")
  public String getComplemento() {
    return complemento;
  }

  public void setComplemento(String complemento) {
    this.complemento = complemento;
  }

  public Endereco bairro(String bairro) {
    this.bairro = bairro;
    return this;
  }

   /**
   * Bairro.
   * @return bairro
  **/
  @ApiModelProperty(value = "Bairro.")
  public String getBairro() {
    return bairro;
  }

  public void setBairro(String bairro) {
    this.bairro = bairro;
  }

  public Endereco cidade(String cidade) {
    this.cidade = cidade;
    return this;
  }

   /**
   * Cidade.
   * @return cidade
  **/
  @ApiModelProperty(value = "Cidade.")
  public String getCidade() {
    return cidade;
  }

  public void setCidade(String cidade) {
    this.cidade = cidade;
  }

  public Endereco uf(String uf) {
    this.uf = uf;
    return this;
  }

   /**
   * Unidade federativa do endereço.
   * @return uf
  **/
  @ApiModelProperty(value = "Unidade federativa do endereço.")
  public String getUf() {
    return uf;
  }

  public void setUf(String uf) {
    this.uf = uf;
  }

  public Endereco cep(Long cep) {
    this.cep = cep;
    return this;
  }

   /**
   * Cep do endereço.
   * @return cep
  **/
  @ApiModelProperty(value = "Cep do endereço.")
  public Long getCep() {
    return cep;
  }

  public void setCep(Long cep) {
    this.cep = cep;
  }

  public Endereco tempoMes(Integer tempoMes) {
    this.tempoMes = tempoMes;
    return this;
  }

   /**
   * Desde que mês o cliente tem essa conta.
   * @return tempoMes
  **/
  @ApiModelProperty(value = "Desde que mês o cliente tem essa conta.")
  public Integer getTempoMes() {
    return tempoMes;
  }

  public void setTempoMes(Integer tempoMes) {
    this.tempoMes = tempoMes;
  }

  public Endereco tempoAno(Integer tempoAno) {
    this.tempoAno = tempoAno;
    return this;
  }

   /**
   * Desde que ano o cliente tem essa conta.
   * @return tempoAno
  **/
  @ApiModelProperty(value = "Desde que ano o cliente tem essa conta.")
  public Integer getTempoAno() {
    return tempoAno;
  }

  public void setTempoAno(Integer tempoAno) {
    this.tempoAno = tempoAno;
  }

  public Endereco tipoResidencia(TipoResidencia tipoResidencia) {
    this.tipoResidencia = tipoResidencia;
    return this;
  }

   /**
   * Get tipoResidencia
   * @return tipoResidencia
  **/
  @ApiModelProperty(value = "")
  public TipoResidencia getTipoResidencia() {
    return tipoResidencia;
  }

  public void setTipoResidencia(TipoResidencia tipoResidencia) {
    this.tipoResidencia = tipoResidencia;
  }

  public Endereco tipoCorrespondencia(TipoCorrespondencia tipoCorrespondencia) {
    this.tipoCorrespondencia = tipoCorrespondencia;
    return this;
  }

   /**
   * Get tipoCorrespondencia
   * @return tipoCorrespondencia
  **/
  @ApiModelProperty(value = "")
  public TipoCorrespondencia getTipoCorrespondencia() {
    return tipoCorrespondencia;
  }

  public void setTipoCorrespondencia(TipoCorrespondencia tipoCorrespondencia) {
    this.tipoCorrespondencia = tipoCorrespondencia;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Endereco endereco = (Endereco) o;
    return Objects.equals(this.logradouro, endereco.logradouro) &&
        Objects.equals(this.numero, endereco.numero) &&
        Objects.equals(this.complemento, endereco.complemento) &&
        Objects.equals(this.bairro, endereco.bairro) &&
        Objects.equals(this.cidade, endereco.cidade) &&
        Objects.equals(this.uf, endereco.uf) &&
        Objects.equals(this.cep, endereco.cep) &&
        Objects.equals(this.tempoMes, endereco.tempoMes) &&
        Objects.equals(this.tempoAno, endereco.tempoAno) &&
        Objects.equals(this.tipoResidencia, endereco.tipoResidencia) &&
        Objects.equals(this.tipoCorrespondencia, endereco.tipoCorrespondencia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(logradouro, numero, complemento, bairro, cidade, uf, cep, tempoMes, tempoAno, tipoResidencia, tipoCorrespondencia);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Endereco {\n");
    
    sb.append("    logradouro: ").append(toIndentedString(logradouro)).append("\n");
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    complemento: ").append(toIndentedString(complemento)).append("\n");
    sb.append("    bairro: ").append(toIndentedString(bairro)).append("\n");
    sb.append("    cidade: ").append(toIndentedString(cidade)).append("\n");
    sb.append("    uf: ").append(toIndentedString(uf)).append("\n");
    sb.append("    cep: ").append(toIndentedString(cep)).append("\n");
    sb.append("    tempoMes: ").append(toIndentedString(tempoMes)).append("\n");
    sb.append("    tempoAno: ").append(toIndentedString(tempoAno)).append("\n");
    sb.append("    tipoResidencia: ").append(toIndentedString(tipoResidencia)).append("\n");
    sb.append("    tipoCorrespondencia: ").append(toIndentedString(tipoCorrespondencia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

