/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enumeration dos estados civil de cliente.
 */
@JsonAdapter(EstadoCivil.Adapter.class)
public enum EstadoCivil {
  
  CASADO("CASADO"),
  
  DIVORCIADO("DIVORCIADO"),
  
  SEPARADO_JUDICIALMENTE("SEPARADO_JUDICIALMENTE"),
  
  OUTROS("OUTROS"),
  
  COMPANHEIRO("COMPANHEIRO"),
  
  SOLTEIRO("SOLTEIRO"),
  
  VIUVO("VIUVO");

  private String value;

  EstadoCivil(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EstadoCivil fromValue(String text) {
    for (EstadoCivil b : EstadoCivil.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<EstadoCivil> {
    @Override
    public void write(final JsonWriter jsonWriter, final EstadoCivil enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EstadoCivil read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EstadoCivil.fromValue(String.valueOf(value));
    }
  }
}

