/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Entidade representando um histórico da proposta.
 */
@ApiModel(description = "Entidade representando um histórico da proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Historico {
  @SerializedName("dataObservacao")
  private LocalDate dataObservacao = null;

  @SerializedName("horaObservacao")
  private String horaObservacao = null;

  @SerializedName("observacao")
  private String observacao = null;

  public Historico dataObservacao(LocalDate dataObservacao) {
    this.dataObservacao = dataObservacao;
    return this;
  }

   /**
   * Data de observação do histórico.
   * @return dataObservacao
  **/
  @ApiModelProperty(value = "Data de observação do histórico.")
  public LocalDate getDataObservacao() {
    return dataObservacao;
  }

  public void setDataObservacao(LocalDate dataObservacao) {
    this.dataObservacao = dataObservacao;
  }

  public Historico horaObservacao(String horaObservacao) {
    this.horaObservacao = horaObservacao;
    return this;
  }

   /**
   * Hora de observação do histórico.
   * @return horaObservacao
  **/
  @ApiModelProperty(value = "Hora de observação do histórico.")
  public String getHoraObservacao() {
    return horaObservacao;
  }

  public void setHoraObservacao(String horaObservacao) {
    this.horaObservacao = horaObservacao;
  }

  public Historico observacao(String observacao) {
    this.observacao = observacao;
    return this;
  }

   /**
   * Observação do histórico.
   * @return observacao
  **/
  @ApiModelProperty(value = "Observação do histórico.")
  public String getObservacao() {
    return observacao;
  }

  public void setObservacao(String observacao) {
    this.observacao = observacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Historico historico = (Historico) o;
    return Objects.equals(this.dataObservacao, historico.dataObservacao) &&
        Objects.equals(this.horaObservacao, historico.horaObservacao) &&
        Objects.equals(this.observacao, historico.observacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataObservacao, horaObservacao, observacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Historico {\n");
    
    sb.append("    dataObservacao: ").append(toIndentedString(dataObservacao)).append("\n");
    sb.append("    horaObservacao: ").append(toIndentedString(horaObservacao)).append("\n");
    sb.append("    observacao: ").append(toIndentedString(observacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

