/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enumeration de indicativo de Sim ou Não.
 */
@JsonAdapter(IndicativoSimNao.Adapter.class)
public enum IndicativoSimNao {
  
  SIM("SIM"),
  
  NAO("NAO");

  private String value;

  IndicativoSimNao(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IndicativoSimNao fromValue(String text) {
    for (IndicativoSimNao b : IndicativoSimNao.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<IndicativoSimNao> {
    @Override
    public void write(final JsonWriter jsonWriter, final IndicativoSimNao enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IndicativoSimNao read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IndicativoSimNao.fromValue(String.valueOf(value));
    }
  }
}

