/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enumeration das nacionalidades do cliente.
 */
@JsonAdapter(Nacionalidade.Adapter.class)
public enum Nacionalidade {
  
  BRASILEIRO_NATO("BRASILEIRO_NATO"),
  
  ESTRANGEIRO("ESTRANGEIRO"),
  
  ESTRANGEIRO_RESIDENTE("ESTRANGEIRO_RESIDENTE"),
  
  BRASILEIRO_NATURALIZADO("BRASILEIRO_NATURALIZADO");

  private String value;

  Nacionalidade(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Nacionalidade fromValue(String text) {
    for (Nacionalidade b : Nacionalidade.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Nacionalidade> {
    @Override
    public void write(final JsonWriter jsonWriter, final Nacionalidade enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Nacionalidade read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Nacionalidade.fromValue(String.valueOf(value));
    }
  }
}

