/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Entidade representando uma pendência.
 */
@ApiModel(description = "Entidade representando uma pendência.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Pendencia {
  @SerializedName("data")
  private LocalDate data = null;

  @SerializedName("descricao")
  private String descricao = null;

  @SerializedName("parecer")
  private String parecer = null;

  public Pendencia data(LocalDate data) {
    this.data = data;
    return this;
  }

   /**
   * Data da pendência.
   * @return data
  **/
  @ApiModelProperty(value = "Data da pendência.")
  public LocalDate getData() {
    return data;
  }

  public void setData(LocalDate data) {
    this.data = data;
  }

  public Pendencia descricao(String descricao) {
    this.descricao = descricao;
    return this;
  }

   /**
   * Descrição da pendência.
   * @return descricao
  **/
  @ApiModelProperty(value = "Descrição da pendência.")
  public String getDescricao() {
    return descricao;
  }

  public void setDescricao(String descricao) {
    this.descricao = descricao;
  }

  public Pendencia parecer(String parecer) {
    this.parecer = parecer;
    return this;
  }

   /**
   * Parecer da pendência.
   * @return parecer
  **/
  @ApiModelProperty(value = "Parecer da pendência.")
  public String getParecer() {
    return parecer;
  }

  public void setParecer(String parecer) {
    this.parecer = parecer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Pendencia pendencia = (Pendencia) o;
    return Objects.equals(this.data, pendencia.data) &&
        Objects.equals(this.descricao, pendencia.descricao) &&
        Objects.equals(this.parecer, pendencia.parecer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, descricao, parecer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Pendencia {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    descricao: ").append(toIndentedString(descricao)).append("\n");
    sb.append("    parecer: ").append(toIndentedString(parecer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

