/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Candidato;
import io.swagger.client.model.TipoSeguro;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Entidade representando uma pré-proposta.
 */
@ApiModel(description = "Entidade representando uma pré-proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class PreProposta {
  @SerializedName("operador")
  private String operador = null;

  @SerializedName("codigoProduto")
  private String codigoProduto = null;

  @SerializedName("valorCompra")
  private Double valorCompra = null;

  @SerializedName("valorPrestacao")
  private Double valorPrestacao = null;

  @SerializedName("prazoPagamento")
  private String prazoPagamento = null;

  @SerializedName("tipoSeguro")
  private TipoSeguro tipoSeguro = null;

  @SerializedName("dataVencimentoPrimeiraParcela")
  private LocalDate dataVencimentoPrimeiraParcela = null;

  @SerializedName("candidato")
  private Candidato candidato = null;

  public PreProposta operador(String operador) {
    this.operador = operador;
    return this;
  }

   /**
   * Identificação do operador.
   * @return operador
  **/
  @ApiModelProperty(value = "Identificação do operador.")
  public String getOperador() {
    return operador;
  }

  public void setOperador(String operador) {
    this.operador = operador;
  }

  public PreProposta codigoProduto(String codigoProduto) {
    this.codigoProduto = codigoProduto;
    return this;
  }

   /**
   * Código do produto. Pelo Produto se descobre também a família de produto.
   * @return codigoProduto
  **/
  @ApiModelProperty(value = "Código do produto. Pelo Produto se descobre também a família de produto.")
  public String getCodigoProduto() {
    return codigoProduto;
  }

  public void setCodigoProduto(String codigoProduto) {
    this.codigoProduto = codigoProduto;
  }

  public PreProposta valorCompra(Double valorCompra) {
    this.valorCompra = valorCompra;
    return this;
  }

   /**
   * Valor da compra sem entrada (neste caso valor da prestação &#x3D; zero).
   * @return valorCompra
  **/
  @ApiModelProperty(value = "Valor da compra sem entrada (neste caso valor da prestação = zero).")
  public Double getValorCompra() {
    return valorCompra;
  }

  public void setValorCompra(Double valorCompra) {
    this.valorCompra = valorCompra;
  }

  public PreProposta valorPrestacao(Double valorPrestacao) {
    this.valorPrestacao = valorPrestacao;
    return this;
  }

   /**
   * Valor da PMT a (neste caso valor da compra &#x3D; zero/ valor da entrada &#x3D; 0).
   * @return valorPrestacao
  **/
  @ApiModelProperty(value = "Valor da PMT a (neste caso valor da compra = zero/ valor da entrada = 0).")
  public Double getValorPrestacao() {
    return valorPrestacao;
  }

  public void setValorPrestacao(Double valorPrestacao) {
    this.valorPrestacao = valorPrestacao;
  }

  public PreProposta prazoPagamento(String prazoPagamento) {
    this.prazoPagamento = prazoPagamento;
    return this;
  }

   /**
   * Prazo de pagamento.
   * @return prazoPagamento
  **/
  @ApiModelProperty(value = "Prazo de pagamento.")
  public String getPrazoPagamento() {
    return prazoPagamento;
  }

  public void setPrazoPagamento(String prazoPagamento) {
    this.prazoPagamento = prazoPagamento;
  }

  public PreProposta tipoSeguro(TipoSeguro tipoSeguro) {
    this.tipoSeguro = tipoSeguro;
    return this;
  }

   /**
   * Get tipoSeguro
   * @return tipoSeguro
  **/
  @ApiModelProperty(value = "")
  public TipoSeguro getTipoSeguro() {
    return tipoSeguro;
  }

  public void setTipoSeguro(TipoSeguro tipoSeguro) {
    this.tipoSeguro = tipoSeguro;
  }

  public PreProposta dataVencimentoPrimeiraParcela(LocalDate dataVencimentoPrimeiraParcela) {
    this.dataVencimentoPrimeiraParcela = dataVencimentoPrimeiraParcela;
    return this;
  }

   /**
   * Data de vencimento da 1ª parcela. Verificar se está coerente com a Carência mínima e máxima combinada com a financeira (dd-mm-aaaa).
   * @return dataVencimentoPrimeiraParcela
  **/
  @ApiModelProperty(value = "Data de vencimento da 1ª parcela. Verificar se está coerente com a Carência mínima e máxima combinada com a financeira (dd-mm-aaaa).")
  public LocalDate getDataVencimentoPrimeiraParcela() {
    return dataVencimentoPrimeiraParcela;
  }

  public void setDataVencimentoPrimeiraParcela(LocalDate dataVencimentoPrimeiraParcela) {
    this.dataVencimentoPrimeiraParcela = dataVencimentoPrimeiraParcela;
  }

  public PreProposta candidato(Candidato candidato) {
    this.candidato = candidato;
    return this;
  }

   /**
   * Get candidato
   * @return candidato
  **/
  @ApiModelProperty(value = "")
  public Candidato getCandidato() {
    return candidato;
  }

  public void setCandidato(Candidato candidato) {
    this.candidato = candidato;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreProposta preProposta = (PreProposta) o;
    return Objects.equals(this.operador, preProposta.operador) &&
        Objects.equals(this.codigoProduto, preProposta.codigoProduto) &&
        Objects.equals(this.valorCompra, preProposta.valorCompra) &&
        Objects.equals(this.valorPrestacao, preProposta.valorPrestacao) &&
        Objects.equals(this.prazoPagamento, preProposta.prazoPagamento) &&
        Objects.equals(this.tipoSeguro, preProposta.tipoSeguro) &&
        Objects.equals(this.dataVencimentoPrimeiraParcela, preProposta.dataVencimentoPrimeiraParcela) &&
        Objects.equals(this.candidato, preProposta.candidato);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operador, codigoProduto, valorCompra, valorPrestacao, prazoPagamento, tipoSeguro, dataVencimentoPrimeiraParcela, candidato);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreProposta {\n");
    
    sb.append("    operador: ").append(toIndentedString(operador)).append("\n");
    sb.append("    codigoProduto: ").append(toIndentedString(codigoProduto)).append("\n");
    sb.append("    valorCompra: ").append(toIndentedString(valorCompra)).append("\n");
    sb.append("    valorPrestacao: ").append(toIndentedString(valorPrestacao)).append("\n");
    sb.append("    prazoPagamento: ").append(toIndentedString(prazoPagamento)).append("\n");
    sb.append("    tipoSeguro: ").append(toIndentedString(tipoSeguro)).append("\n");
    sb.append("    dataVencimentoPrimeiraParcela: ").append(toIndentedString(dataVencimentoPrimeiraParcela)).append("\n");
    sb.append("    candidato: ").append(toIndentedString(candidato)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

