/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Cheque;
import io.swagger.client.model.Cliente;
import io.swagger.client.model.DadoAdicional;
import io.swagger.client.model.DadosLiberacao;
import io.swagger.client.model.FormaEnvio;
import io.swagger.client.model.TipoContrato;
import io.swagger.client.model.TipoEfetivacao;
import io.swagger.client.model.TipoSeguro;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * Entidade representando uma proposta.
 */
@ApiModel(description = "Entidade representando uma proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Proposta {
  @SerializedName("numero")
  private String numero = null;

  @SerializedName("dataEmissao")
  private LocalDate dataEmissao = null;

  @SerializedName("dataVencimentoPrimeiraParcela")
  private LocalDate dataVencimentoPrimeiraParcela = null;

  @SerializedName("codigoProduto")
  private String codigoProduto = null;

  @SerializedName("codigoPlanoPagamento")
  private String codigoPlanoPagamento = null;

  @SerializedName("prazoPagamento")
  private String prazoPagamento = null;

  @SerializedName("codigoMidia")
  private String codigoMidia = null;

  @SerializedName("tipoContrato")
  private TipoContrato tipoContrato = null;

  @SerializedName("valorCompra")
  private Double valorCompra = null;

  @SerializedName("valorEntrada")
  private Double valorEntrada = null;

  @SerializedName("valorPrestacao")
  private Double valorPrestacao = null;

  @SerializedName("valorLiberado")
  private Double valorLiberado = null;

  @SerializedName("dadosAdicionais")
  private List<DadoAdicional> dadosAdicionais = null;

  @SerializedName("tipoSeguro")
  private TipoSeguro tipoSeguro = null;

  @SerializedName("clientes")
  private List<Cliente> clientes = null;

  @SerializedName("cheques")
  private List<Cheque> cheques = null;

  @SerializedName("formaEnvio")
  private FormaEnvio formaEnvio = null;

  @SerializedName("dadosLiberacao")
  private DadosLiberacao dadosLiberacao = null;

  @SerializedName("tipoEfetivacao")
  private TipoEfetivacao tipoEfetivacao = null;

  public Proposta numero(String numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Número da proposta.
   * @return numero
  **/
  @ApiModelProperty(value = "Número da proposta.")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public Proposta dataEmissao(LocalDate dataEmissao) {
    this.dataEmissao = dataEmissao;
    return this;
  }

   /**
   * Data de emissão da Proposta. Não pode ser inferior a data que vai ser liberado o dinheiro. Data base do cálculo do financiamento (dd-mm-aaaa).
   * @return dataEmissao
  **/
  @ApiModelProperty(value = "Data de emissão da Proposta. Não pode ser inferior a data que vai ser liberado o dinheiro. Data base do cálculo do financiamento (dd-mm-aaaa).")
  public LocalDate getDataEmissao() {
    return dataEmissao;
  }

  public void setDataEmissao(LocalDate dataEmissao) {
    this.dataEmissao = dataEmissao;
  }

  public Proposta dataVencimentoPrimeiraParcela(LocalDate dataVencimentoPrimeiraParcela) {
    this.dataVencimentoPrimeiraParcela = dataVencimentoPrimeiraParcela;
    return this;
  }

   /**
   * Data de vencimento da 1ª parcela. Verificar se está coerente com a  Carência mínima e máxima combinada com a financeira (dd-mm-aaaa).
   * @return dataVencimentoPrimeiraParcela
  **/
  @ApiModelProperty(value = "Data de vencimento da 1ª parcela. Verificar se está coerente com a  Carência mínima e máxima combinada com a financeira (dd-mm-aaaa).")
  public LocalDate getDataVencimentoPrimeiraParcela() {
    return dataVencimentoPrimeiraParcela;
  }

  public void setDataVencimentoPrimeiraParcela(LocalDate dataVencimentoPrimeiraParcela) {
    this.dataVencimentoPrimeiraParcela = dataVencimentoPrimeiraParcela;
  }

  public Proposta codigoProduto(String codigoProduto) {
    this.codigoProduto = codigoProduto;
    return this;
  }

   /**
   * Código do produto. Pelo Produto se descobre também a família de produto.
   * @return codigoProduto
  **/
  @ApiModelProperty(value = "Código do produto. Pelo Produto se descobre também a família de produto.")
  public String getCodigoProduto() {
    return codigoProduto;
  }

  public void setCodigoProduto(String codigoProduto) {
    this.codigoProduto = codigoProduto;
  }

  public Proposta codigoPlanoPagamento(String codigoPlanoPagamento) {
    this.codigoPlanoPagamento = codigoPlanoPagamento;
    return this;
  }

   /**
   * Código do plano de pagamentos.
   * @return codigoPlanoPagamento
  **/
  @ApiModelProperty(value = "Código do plano de pagamentos.")
  public String getCodigoPlanoPagamento() {
    return codigoPlanoPagamento;
  }

  public void setCodigoPlanoPagamento(String codigoPlanoPagamento) {
    this.codigoPlanoPagamento = codigoPlanoPagamento;
  }

  public Proposta prazoPagamento(String prazoPagamento) {
    this.prazoPagamento = prazoPagamento;
    return this;
  }

   /**
   * Prazo de pagamento.
   * @return prazoPagamento
  **/
  @ApiModelProperty(value = "Prazo de pagamento.")
  public String getPrazoPagamento() {
    return prazoPagamento;
  }

  public void setPrazoPagamento(String prazoPagamento) {
    this.prazoPagamento = prazoPagamento;
  }

  public Proposta codigoMidia(String codigoMidia) {
    this.codigoMidia = codigoMidia;
    return this;
  }

   /**
   * Informar a origem da proposta.
   * @return codigoMidia
  **/
  @ApiModelProperty(value = "Informar a origem da proposta.")
  public String getCodigoMidia() {
    return codigoMidia;
  }

  public void setCodigoMidia(String codigoMidia) {
    this.codigoMidia = codigoMidia;
  }

  public Proposta tipoContrato(TipoContrato tipoContrato) {
    this.tipoContrato = tipoContrato;
    return this;
  }

   /**
   * Get tipoContrato
   * @return tipoContrato
  **/
  @ApiModelProperty(value = "")
  public TipoContrato getTipoContrato() {
    return tipoContrato;
  }

  public void setTipoContrato(TipoContrato tipoContrato) {
    this.tipoContrato = tipoContrato;
  }

  public Proposta valorCompra(Double valorCompra) {
    this.valorCompra = valorCompra;
    return this;
  }

   /**
   * Valor da compra sem entrada (neste caso valor da prestação &#x3D; zero).
   * @return valorCompra
  **/
  @ApiModelProperty(value = "Valor da compra sem entrada (neste caso valor da prestação = zero).")
  public Double getValorCompra() {
    return valorCompra;
  }

  public void setValorCompra(Double valorCompra) {
    this.valorCompra = valorCompra;
  }

  public Proposta valorEntrada(Double valorEntrada) {
    this.valorEntrada = valorEntrada;
    return this;
  }

   /**
   * Valor da entrada (neste caso valor da prestação &#x3D; zero/ Valor da Compra &lt;&gt; zero).
   * @return valorEntrada
  **/
  @ApiModelProperty(value = "Valor da entrada (neste caso valor da prestação = zero/ Valor da Compra <> zero).")
  public Double getValorEntrada() {
    return valorEntrada;
  }

  public void setValorEntrada(Double valorEntrada) {
    this.valorEntrada = valorEntrada;
  }

  public Proposta valorPrestacao(Double valorPrestacao) {
    this.valorPrestacao = valorPrestacao;
    return this;
  }

   /**
   * Valor da PMT a (neste caso valor da compra &#x3D; zero/ valor da entrada &#x3D; 0).
   * @return valorPrestacao
  **/
  @ApiModelProperty(value = "Valor da PMT a (neste caso valor da compra = zero/ valor da entrada = 0).")
  public Double getValorPrestacao() {
    return valorPrestacao;
  }

  public void setValorPrestacao(Double valorPrestacao) {
    this.valorPrestacao = valorPrestacao;
  }

  public Proposta valorLiberado(Double valorLiberado) {
    this.valorLiberado = valorLiberado;
    return this;
  }

   /**
   * Valor liberado da proposta.
   * @return valorLiberado
  **/
  @ApiModelProperty(value = "Valor liberado da proposta.")
  public Double getValorLiberado() {
    return valorLiberado;
  }

  public void setValorLiberado(Double valorLiberado) {
    this.valorLiberado = valorLiberado;
  }

  public Proposta dadosAdicionais(List<DadoAdicional> dadosAdicionais) {
    this.dadosAdicionais = dadosAdicionais;
    return this;
  }

  public Proposta addDadosAdicionaisItem(DadoAdicional dadosAdicionaisItem) {
    if (this.dadosAdicionais == null) {
      this.dadosAdicionais = new ArrayList<DadoAdicional>();
    }
    this.dadosAdicionais.add(dadosAdicionaisItem);
    return this;
  }

   /**
   * Get dadosAdicionais
   * @return dadosAdicionais
  **/
  @ApiModelProperty(value = "")
  public List<DadoAdicional> getDadosAdicionais() {
    return dadosAdicionais;
  }

  public void setDadosAdicionais(List<DadoAdicional> dadosAdicionais) {
    this.dadosAdicionais = dadosAdicionais;
  }

  public Proposta tipoSeguro(TipoSeguro tipoSeguro) {
    this.tipoSeguro = tipoSeguro;
    return this;
  }

   /**
   * Get tipoSeguro
   * @return tipoSeguro
  **/
  @ApiModelProperty(value = "")
  public TipoSeguro getTipoSeguro() {
    return tipoSeguro;
  }

  public void setTipoSeguro(TipoSeguro tipoSeguro) {
    this.tipoSeguro = tipoSeguro;
  }

  public Proposta clientes(List<Cliente> clientes) {
    this.clientes = clientes;
    return this;
  }

  public Proposta addClientesItem(Cliente clientesItem) {
    if (this.clientes == null) {
      this.clientes = new ArrayList<Cliente>();
    }
    this.clientes.add(clientesItem);
    return this;
  }

   /**
   * Get clientes
   * @return clientes
  **/
  @ApiModelProperty(value = "")
  public List<Cliente> getClientes() {
    return clientes;
  }

  public void setClientes(List<Cliente> clientes) {
    this.clientes = clientes;
  }

  public Proposta cheques(List<Cheque> cheques) {
    this.cheques = cheques;
    return this;
  }

  public Proposta addChequesItem(Cheque chequesItem) {
    if (this.cheques == null) {
      this.cheques = new ArrayList<Cheque>();
    }
    this.cheques.add(chequesItem);
    return this;
  }

   /**
   * Get cheques
   * @return cheques
  **/
  @ApiModelProperty(value = "")
  public List<Cheque> getCheques() {
    return cheques;
  }

  public void setCheques(List<Cheque> cheques) {
    this.cheques = cheques;
  }

  public Proposta formaEnvio(FormaEnvio formaEnvio) {
    this.formaEnvio = formaEnvio;
    return this;
  }

   /**
   * Get formaEnvio
   * @return formaEnvio
  **/
  @ApiModelProperty(value = "")
  public FormaEnvio getFormaEnvio() {
    return formaEnvio;
  }

  public void setFormaEnvio(FormaEnvio formaEnvio) {
    this.formaEnvio = formaEnvio;
  }

  public Proposta dadosLiberacao(DadosLiberacao dadosLiberacao) {
    this.dadosLiberacao = dadosLiberacao;
    return this;
  }

   /**
   * Get dadosLiberacao
   * @return dadosLiberacao
  **/
  @ApiModelProperty(value = "")
  public DadosLiberacao getDadosLiberacao() {
    return dadosLiberacao;
  }

  public void setDadosLiberacao(DadosLiberacao dadosLiberacao) {
    this.dadosLiberacao = dadosLiberacao;
  }

  public Proposta tipoEfetivacao(TipoEfetivacao tipoEfetivacao) {
    this.tipoEfetivacao = tipoEfetivacao;
    return this;
  }

   /**
   * Get tipoEfetivacao
   * @return tipoEfetivacao
  **/
  @ApiModelProperty(value = "")
  public TipoEfetivacao getTipoEfetivacao() {
    return tipoEfetivacao;
  }

  public void setTipoEfetivacao(TipoEfetivacao tipoEfetivacao) {
    this.tipoEfetivacao = tipoEfetivacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Proposta proposta = (Proposta) o;
    return Objects.equals(this.numero, proposta.numero) &&
        Objects.equals(this.dataEmissao, proposta.dataEmissao) &&
        Objects.equals(this.dataVencimentoPrimeiraParcela, proposta.dataVencimentoPrimeiraParcela) &&
        Objects.equals(this.codigoProduto, proposta.codigoProduto) &&
        Objects.equals(this.codigoPlanoPagamento, proposta.codigoPlanoPagamento) &&
        Objects.equals(this.prazoPagamento, proposta.prazoPagamento) &&
        Objects.equals(this.codigoMidia, proposta.codigoMidia) &&
        Objects.equals(this.tipoContrato, proposta.tipoContrato) &&
        Objects.equals(this.valorCompra, proposta.valorCompra) &&
        Objects.equals(this.valorEntrada, proposta.valorEntrada) &&
        Objects.equals(this.valorPrestacao, proposta.valorPrestacao) &&
        Objects.equals(this.valorLiberado, proposta.valorLiberado) &&
        Objects.equals(this.dadosAdicionais, proposta.dadosAdicionais) &&
        Objects.equals(this.tipoSeguro, proposta.tipoSeguro) &&
        Objects.equals(this.clientes, proposta.clientes) &&
        Objects.equals(this.cheques, proposta.cheques) &&
        Objects.equals(this.formaEnvio, proposta.formaEnvio) &&
        Objects.equals(this.dadosLiberacao, proposta.dadosLiberacao) &&
        Objects.equals(this.tipoEfetivacao, proposta.tipoEfetivacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, dataEmissao, dataVencimentoPrimeiraParcela, codigoProduto, codigoPlanoPagamento, prazoPagamento, codigoMidia, tipoContrato, valorCompra, valorEntrada, valorPrestacao, valorLiberado, dadosAdicionais, tipoSeguro, clientes, cheques, formaEnvio, dadosLiberacao, tipoEfetivacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Proposta {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    dataEmissao: ").append(toIndentedString(dataEmissao)).append("\n");
    sb.append("    dataVencimentoPrimeiraParcela: ").append(toIndentedString(dataVencimentoPrimeiraParcela)).append("\n");
    sb.append("    codigoProduto: ").append(toIndentedString(codigoProduto)).append("\n");
    sb.append("    codigoPlanoPagamento: ").append(toIndentedString(codigoPlanoPagamento)).append("\n");
    sb.append("    prazoPagamento: ").append(toIndentedString(prazoPagamento)).append("\n");
    sb.append("    codigoMidia: ").append(toIndentedString(codigoMidia)).append("\n");
    sb.append("    tipoContrato: ").append(toIndentedString(tipoContrato)).append("\n");
    sb.append("    valorCompra: ").append(toIndentedString(valorCompra)).append("\n");
    sb.append("    valorEntrada: ").append(toIndentedString(valorEntrada)).append("\n");
    sb.append("    valorPrestacao: ").append(toIndentedString(valorPrestacao)).append("\n");
    sb.append("    valorLiberado: ").append(toIndentedString(valorLiberado)).append("\n");
    sb.append("    dadosAdicionais: ").append(toIndentedString(dadosAdicionais)).append("\n");
    sb.append("    tipoSeguro: ").append(toIndentedString(tipoSeguro)).append("\n");
    sb.append("    clientes: ").append(toIndentedString(clientes)).append("\n");
    sb.append("    cheques: ").append(toIndentedString(cheques)).append("\n");
    sb.append("    formaEnvio: ").append(toIndentedString(formaEnvio)).append("\n");
    sb.append("    dadosLiberacao: ").append(toIndentedString(dadosLiberacao)).append("\n");
    sb.append("    tipoEfetivacao: ").append(toIndentedString(tipoEfetivacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

