/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.LocalDate;

/**
 * Objeto de resposta da proposta.
 */
@ApiModel(description = "Objeto de resposta da proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class PropostaResponse {
  @SerializedName("numero")
  private String numero = null;

  @SerializedName("data")
  private LocalDate data = null;

  @SerializedName("codigoLoja")
  private String codigoLoja = null;

  @SerializedName("codigoLojista")
  private String codigoLojista = null;

  @SerializedName("codigoProduto")
  private String codigoProduto = null;

  @SerializedName("valor")
  private Double valor = null;

  @SerializedName("tipo")
  private String tipo = null;

  @SerializedName("situacao")
  private String situacao = null;

  public PropostaResponse numero(String numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Número da proposta.
   * @return numero
  **/
  @ApiModelProperty(value = "Número da proposta.")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public PropostaResponse data(LocalDate data) {
    this.data = data;
    return this;
  }

   /**
   * Data da proposta.
   * @return data
  **/
  @ApiModelProperty(value = "Data da proposta.")
  public LocalDate getData() {
    return data;
  }

  public void setData(LocalDate data) {
    this.data = data;
  }

  public PropostaResponse codigoLoja(String codigoLoja) {
    this.codigoLoja = codigoLoja;
    return this;
  }

   /**
   * Código da loja da proposta.
   * @return codigoLoja
  **/
  @ApiModelProperty(value = "Código da loja da proposta.")
  public String getCodigoLoja() {
    return codigoLoja;
  }

  public void setCodigoLoja(String codigoLoja) {
    this.codigoLoja = codigoLoja;
  }

  public PropostaResponse codigoLojista(String codigoLojista) {
    this.codigoLojista = codigoLojista;
    return this;
  }

   /**
   * Código do lojista da proposta.
   * @return codigoLojista
  **/
  @ApiModelProperty(value = "Código do lojista da proposta.")
  public String getCodigoLojista() {
    return codigoLojista;
  }

  public void setCodigoLojista(String codigoLojista) {
    this.codigoLojista = codigoLojista;
  }

  public PropostaResponse codigoProduto(String codigoProduto) {
    this.codigoProduto = codigoProduto;
    return this;
  }

   /**
   * Código do produto da proposta.
   * @return codigoProduto
  **/
  @ApiModelProperty(value = "Código do produto da proposta.")
  public String getCodigoProduto() {
    return codigoProduto;
  }

  public void setCodigoProduto(String codigoProduto) {
    this.codigoProduto = codigoProduto;
  }

  public PropostaResponse valor(Double valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Valor da proposta.
   * @return valor
  **/
  @ApiModelProperty(value = "Valor da proposta.")
  public Double getValor() {
    return valor;
  }

  public void setValor(Double valor) {
    this.valor = valor;
  }

  public PropostaResponse tipo(String tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Tipo da proposta.
   * @return tipo
  **/
  @ApiModelProperty(value = "Tipo da proposta.")
  public String getTipo() {
    return tipo;
  }

  public void setTipo(String tipo) {
    this.tipo = tipo;
  }

  public PropostaResponse situacao(String situacao) {
    this.situacao = situacao;
    return this;
  }

   /**
   * Situação da proposta.
   * @return situacao
  **/
  @ApiModelProperty(value = "Situação da proposta.")
  public String getSituacao() {
    return situacao;
  }

  public void setSituacao(String situacao) {
    this.situacao = situacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PropostaResponse propostaResponse = (PropostaResponse) o;
    return Objects.equals(this.numero, propostaResponse.numero) &&
        Objects.equals(this.data, propostaResponse.data) &&
        Objects.equals(this.codigoLoja, propostaResponse.codigoLoja) &&
        Objects.equals(this.codigoLojista, propostaResponse.codigoLojista) &&
        Objects.equals(this.codigoProduto, propostaResponse.codigoProduto) &&
        Objects.equals(this.valor, propostaResponse.valor) &&
        Objects.equals(this.tipo, propostaResponse.tipo) &&
        Objects.equals(this.situacao, propostaResponse.situacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numero, data, codigoLoja, codigoLojista, codigoProduto, valor, tipo, situacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PropostaResponse {\n");
    
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    codigoLoja: ").append(toIndentedString(codigoLoja)).append("\n");
    sb.append("    codigoLojista: ").append(toIndentedString(codigoLojista)).append("\n");
    sb.append("    codigoProduto: ").append(toIndentedString(codigoProduto)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    situacao: ").append(toIndentedString(situacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

