/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Telefone;
import java.io.IOException;

/**
 * Entidade representando uma referência pessoal
 */
@ApiModel(description = "Entidade representando uma referência pessoal")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class ReferenciaPessoal {
  @SerializedName("nome")
  private String nome = null;

  @SerializedName("relacionamento")
  private String relacionamento = null;

  @SerializedName("telefone")
  private Telefone telefone = null;

  public ReferenciaPessoal nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Nome da referência pessoal.
   * @return nome
  **/
  @ApiModelProperty(value = "Nome da referência pessoal.")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public ReferenciaPessoal relacionamento(String relacionamento) {
    this.relacionamento = relacionamento;
    return this;
  }

   /**
   * Relacionamento com a referência pessoal.
   * @return relacionamento
  **/
  @ApiModelProperty(value = "Relacionamento com a referência pessoal.")
  public String getRelacionamento() {
    return relacionamento;
  }

  public void setRelacionamento(String relacionamento) {
    this.relacionamento = relacionamento;
  }

  public ReferenciaPessoal telefone(Telefone telefone) {
    this.telefone = telefone;
    return this;
  }

   /**
   * Get telefone
   * @return telefone
  **/
  @ApiModelProperty(value = "")
  public Telefone getTelefone() {
    return telefone;
  }

  public void setTelefone(Telefone telefone) {
    this.telefone = telefone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReferenciaPessoal referenciaPessoal = (ReferenciaPessoal) o;
    return Objects.equals(this.nome, referenciaPessoal.nome) &&
        Objects.equals(this.relacionamento, referenciaPessoal.relacionamento) &&
        Objects.equals(this.telefone, referenciaPessoal.telefone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nome, relacionamento, telefone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReferenciaPessoal {\n");
    
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    relacionamento: ").append(toIndentedString(relacionamento)).append("\n");
    sb.append("    telefone: ").append(toIndentedString(telefone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

