/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Endereco;
import io.swagger.client.model.Telefone;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.LocalDate;

/**
 * Entidade que representa uma renda adicional
 */
@ApiModel(description = "Entidade que representa uma renda adicional")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class RendaAdicional {
  @SerializedName("valor")
  private Double valor = null;

  @SerializedName("cnpj")
  private String cnpj = null;

  @SerializedName("dataAdmissao")
  private LocalDate dataAdmissao = null;

  @SerializedName("nomeEmpresa")
  private String nomeEmpresa = null;

  @SerializedName("numeroBeneficio")
  private String numeroBeneficio = null;

  @SerializedName("especieBeneficio")
  private String especieBeneficio = null;

  @SerializedName("telefones")
  private List<Telefone> telefones = null;

  @SerializedName("endereco")
  private Endereco endereco = null;

  public RendaAdicional valor(Double valor) {
    this.valor = valor;
    return this;
  }

   /**
   * Valor da renda adicional.
   * @return valor
  **/
  @ApiModelProperty(value = "Valor da renda adicional.")
  public Double getValor() {
    return valor;
  }

  public void setValor(Double valor) {
    this.valor = valor;
  }

  public RendaAdicional cnpj(String cnpj) {
    this.cnpj = cnpj;
    return this;
  }

   /**
   * CNPJ da empresa.
   * @return cnpj
  **/
  @ApiModelProperty(value = "CNPJ da empresa.")
  public String getCnpj() {
    return cnpj;
  }

  public void setCnpj(String cnpj) {
    this.cnpj = cnpj;
  }

  public RendaAdicional dataAdmissao(LocalDate dataAdmissao) {
    this.dataAdmissao = dataAdmissao;
    return this;
  }

   /**
   * Data da admissão. (aaaa-mm-dd).
   * @return dataAdmissao
  **/
  @ApiModelProperty(value = "Data da admissão. (aaaa-mm-dd).")
  public LocalDate getDataAdmissao() {
    return dataAdmissao;
  }

  public void setDataAdmissao(LocalDate dataAdmissao) {
    this.dataAdmissao = dataAdmissao;
  }

  public RendaAdicional nomeEmpresa(String nomeEmpresa) {
    this.nomeEmpresa = nomeEmpresa;
    return this;
  }

   /**
   * Nome da empresa.
   * @return nomeEmpresa
  **/
  @ApiModelProperty(value = "Nome da empresa.")
  public String getNomeEmpresa() {
    return nomeEmpresa;
  }

  public void setNomeEmpresa(String nomeEmpresa) {
    this.nomeEmpresa = nomeEmpresa;
  }

  public RendaAdicional numeroBeneficio(String numeroBeneficio) {
    this.numeroBeneficio = numeroBeneficio;
    return this;
  }

   /**
   * Número do benefício.
   * @return numeroBeneficio
  **/
  @ApiModelProperty(value = "Número do benefício.")
  public String getNumeroBeneficio() {
    return numeroBeneficio;
  }

  public void setNumeroBeneficio(String numeroBeneficio) {
    this.numeroBeneficio = numeroBeneficio;
  }

  public RendaAdicional especieBeneficio(String especieBeneficio) {
    this.especieBeneficio = especieBeneficio;
    return this;
  }

   /**
   * Espécie do benefício.
   * @return especieBeneficio
  **/
  @ApiModelProperty(value = "Espécie do benefício.")
  public String getEspecieBeneficio() {
    return especieBeneficio;
  }

  public void setEspecieBeneficio(String especieBeneficio) {
    this.especieBeneficio = especieBeneficio;
  }

  public RendaAdicional telefones(List<Telefone> telefones) {
    this.telefones = telefones;
    return this;
  }

  public RendaAdicional addTelefonesItem(Telefone telefonesItem) {
    if (this.telefones == null) {
      this.telefones = new ArrayList<Telefone>();
    }
    this.telefones.add(telefonesItem);
    return this;
  }

   /**
   * Get telefones
   * @return telefones
  **/
  @ApiModelProperty(value = "")
  public List<Telefone> getTelefones() {
    return telefones;
  }

  public void setTelefones(List<Telefone> telefones) {
    this.telefones = telefones;
  }

  public RendaAdicional endereco(Endereco endereco) {
    this.endereco = endereco;
    return this;
  }

   /**
   * Get endereco
   * @return endereco
  **/
  @ApiModelProperty(value = "")
  public Endereco getEndereco() {
    return endereco;
  }

  public void setEndereco(Endereco endereco) {
    this.endereco = endereco;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RendaAdicional rendaAdicional = (RendaAdicional) o;
    return Objects.equals(this.valor, rendaAdicional.valor) &&
        Objects.equals(this.cnpj, rendaAdicional.cnpj) &&
        Objects.equals(this.dataAdmissao, rendaAdicional.dataAdmissao) &&
        Objects.equals(this.nomeEmpresa, rendaAdicional.nomeEmpresa) &&
        Objects.equals(this.numeroBeneficio, rendaAdicional.numeroBeneficio) &&
        Objects.equals(this.especieBeneficio, rendaAdicional.especieBeneficio) &&
        Objects.equals(this.telefones, rendaAdicional.telefones) &&
        Objects.equals(this.endereco, rendaAdicional.endereco);
  }

  @Override
  public int hashCode() {
    return Objects.hash(valor, cnpj, dataAdmissao, nomeEmpresa, numeroBeneficio, especieBeneficio, telefones, endereco);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RendaAdicional {\n");
    
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("    cnpj: ").append(toIndentedString(cnpj)).append("\n");
    sb.append("    dataAdmissao: ").append(toIndentedString(dataAdmissao)).append("\n");
    sb.append("    nomeEmpresa: ").append(toIndentedString(nomeEmpresa)).append("\n");
    sb.append("    numeroBeneficio: ").append(toIndentedString(numeroBeneficio)).append("\n");
    sb.append("    especieBeneficio: ").append(toIndentedString(especieBeneficio)).append("\n");
    sb.append("    telefones: ").append(toIndentedString(telefones)).append("\n");
    sb.append("    endereco: ").append(toIndentedString(endereco)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

