/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Objeto de resposta para o status da proposta.
 */
@ApiModel(description = "Objeto de resposta para o status da proposta.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class StatusPropostaResponse {
  @SerializedName("descricaoSituacao")
  private String descricaoSituacao = null;

  public StatusPropostaResponse descricaoSituacao(String descricaoSituacao) {
    this.descricaoSituacao = descricaoSituacao;
    return this;
  }

   /**
   * Status da proposta.
   * @return descricaoSituacao
  **/
  @ApiModelProperty(value = "Status da proposta.")
  public String getDescricaoSituacao() {
    return descricaoSituacao;
  }

  public void setDescricaoSituacao(String descricaoSituacao) {
    this.descricaoSituacao = descricaoSituacao;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusPropostaResponse statusPropostaResponse = (StatusPropostaResponse) o;
    return Objects.equals(this.descricaoSituacao, statusPropostaResponse.descricaoSituacao);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descricaoSituacao);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusPropostaResponse {\n");
    
    sb.append("    descricaoSituacao: ").append(toIndentedString(descricaoSituacao)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

