/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TipoTelefone;
import java.io.IOException;

/**
 * Entidade representando um telefone.
 */
@ApiModel(description = "Entidade representando um telefone.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-10T12:41:57.739Z")
public class Telefone {
  @SerializedName("tipo")
  private TipoTelefone tipo = null;

  @SerializedName("ddd")
  private String ddd = null;

  @SerializedName("numero")
  private String numero = null;

  @SerializedName("ramal")
  private String ramal = null;

  public Telefone tipo(TipoTelefone tipo) {
    this.tipo = tipo;
    return this;
  }

   /**
   * Get tipo
   * @return tipo
  **/
  @ApiModelProperty(value = "")
  public TipoTelefone getTipo() {
    return tipo;
  }

  public void setTipo(TipoTelefone tipo) {
    this.tipo = tipo;
  }

  public Telefone ddd(String ddd) {
    this.ddd = ddd;
    return this;
  }

   /**
   * Código de discagem direta a distância.
   * @return ddd
  **/
  @ApiModelProperty(value = "Código de discagem direta a distância.")
  public String getDdd() {
    return ddd;
  }

  public void setDdd(String ddd) {
    this.ddd = ddd;
  }

  public Telefone numero(String numero) {
    this.numero = numero;
    return this;
  }

   /**
   * Número do telefone.
   * @return numero
  **/
  @ApiModelProperty(value = "Número do telefone.")
  public String getNumero() {
    return numero;
  }

  public void setNumero(String numero) {
    this.numero = numero;
  }

  public Telefone ramal(String ramal) {
    this.ramal = ramal;
    return this;
  }

   /**
   * Ramal do telefone.
   * @return ramal
  **/
  @ApiModelProperty(value = "Ramal do telefone.")
  public String getRamal() {
    return ramal;
  }

  public void setRamal(String ramal) {
    this.ramal = ramal;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Telefone telefone = (Telefone) o;
    return Objects.equals(this.tipo, telefone.tipo) &&
        Objects.equals(this.ddd, telefone.ddd) &&
        Objects.equals(this.numero, telefone.numero) &&
        Objects.equals(this.ramal, telefone.ramal);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tipo, ddd, numero, ramal);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Telefone {\n");
    
    sb.append("    tipo: ").append(toIndentedString(tipo)).append("\n");
    sb.append("    ddd: ").append(toIndentedString(ddd)).append("\n");
    sb.append("    numero: ").append(toIndentedString(numero)).append("\n");
    sb.append("    ramal: ").append(toIndentedString(ramal)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

