/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enumeration dos tipos de residência do endereço.
 */
@JsonAdapter(TipoResidencia.Adapter.class)
public enum TipoResidencia {
  
  PROPRIA_QUITADA("PROPRIA_QUITADA"),
  
  PROPRIA_FINANCIADA("PROPRIA_FINANCIADA"),
  
  ALUGADA("ALUGADA"),
  
  PARENTES("PARENTES"),
  
  FUNCIONAL("FUNCIONAL"),
  
  OUTROS("OUTROS");

  private String value;

  TipoResidencia(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TipoResidencia fromValue(String text) {
    for (TipoResidencia b : TipoResidencia.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TipoResidencia> {
    @Override
    public void write(final JsonWriter jsonWriter, final TipoResidencia enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TipoResidencia read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TipoResidencia.fromValue(String.valueOf(value));
    }
  }
}

