/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enumeration dos tipos de contrato da proposta.
 */
@JsonAdapter(TipoContrato.Adapter.class)
public enum TipoContrato {
  
  CCB("CCB"),
  
  MUTUO("MUTUO"),
  
  ACEITE("ACEITE");

  private String value;

  TipoContrato(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TipoContrato fromValue(String text) {
    for (TipoContrato b : TipoContrato.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TipoContrato> {
    @Override
    public void write(final JsonWriter jsonWriter, final TipoContrato enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TipoContrato read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TipoContrato.fromValue(String.valueOf(value));
    }
  }
}

