/*
 * Gestão de Propostas
 * API de Gestão de Propostas.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Enumeration dos tipos de contas.
 */
@JsonAdapter(TipoConta.Adapter.class)
public enum TipoConta {
  
  CHEQUE_ESPECIAL("CHEQUE_ESPECIAL"),
  
  CONTA_SIMPLES("CONTA_SIMPLES");

  private String value;

  TipoConta(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static TipoConta fromValue(String text) {
    for (TipoConta b : TipoConta.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<TipoConta> {
    @Override
    public void write(final JsonWriter jsonWriter, final TipoConta enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public TipoConta read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return TipoConta.fromValue(String.valueOf(value));
    }
  }
}

